### ISSUE TITLE
Codes about the reconstructed vedios

### ISSUE THREAD

**Issue by TomTomTommi** [facebookresearch/dynamic_stereo#10]
Hi, very interesting work! 
I wonder are there any codes for the reconstructed videos shown on the project page? After obtaining the output disparity, what should I do to convert it to the depth information and then get the final reconstructed videos?

**Comment by nikitakaraevv** [comment]
Hi @TomTomTommi, thank you! 
During evaluation, visualization can be done by passing an additional flag, `visualize_interval=1`. If you want to visualize predictions on your own sequences, you can do it with the following function: https://github.com/facebookresearch/dynamic_stereo/blob/c5077aa19f73cf3e51e363bf8a3796c85eb2eaa0/evaluation/core/evaluator.py#L129
