### ISSUE TITLE
Table 5 Results

### ISSUE THREAD

**Issue by TomTomTommi** [facebookresearch/dynamic_stereo#11]
Hi,
I followed the suggested command to evaluate the trained dynamicstereo model: `python ./evaluation/evaluate.py --config-name eval_dynamic_replica_40_frames \
 MODEL.model_name=DynamicStereoModel exp_dir=./outputs/test_dynamic_replica_ds \
 MODEL.DynamicStereoModel.model_weights=./checkpoints/dynamic_stereo_sf.pth `

However, the results don't match Table 5's results. I checked the code and it seemed that the dataset split should be modified to `'test'`. Besides, the frame amount used in testing should reset as 150 instead of 40, right? `(--config-name eval_dynamic_replica_150_frames)`

Plus, after modifying the above setting, I got the results(dynamic_stereo_sf.pth on DS testset ) as follows:
```
===== Perception results =====
-----------------------  --------
disp_epe_bad_0.5px       8.04176
disp_epe_bad_1px         3.39895
disp_epe_bad_2px         1.49977
disp_epe_bad_3px         0.96465
disp_epe_mean            0.238692
disp_temp_epe_bad_0.5px  1.52825
disp_temp_epe_bad_1px    0.731156
disp_temp_epe_bad_2px    0.363196
disp_temp_epe_bad_3px    0.238875
disp_temp_epe_mean       0.082913
-----------------------  --------
```
I just want to double check that the results are correct, right?

**Comment by nikitakaraevv** [comment]
Hi @TomTomTommi, yes, this likely should be corrected; an evaluation should be done on the test split with 150 frames. The results seem to be quite close to what we report in the paper (these numbers are even slightly better). Can you also share the results that you obtained after evaluating on the 'valid' split with 40 and 150 frames?

**Comment by TomTomTommi** [comment]
The results on the 'valid' split with 150 framses are as follows (dynamic_stereo_dr_sf.pth on DS testset):
```
===== Perception results =====
-----------------------  --------
disp_epe_bad_0.5px       7.2633
disp_epe_bad_1px         3.2381
disp_epe_bad_2px         1.90933
disp_epe_bad_3px         1.56244
disp_epe_mean            0.588427
disp_temp_epe_bad_0.5px  2.70312
disp_temp_epe_bad_1px    1.51765
disp_temp_epe_bad_2px    0.674561
disp_temp_epe_bad_3px    0.405375
disp_temp_epe_mean       0.121137
-----------------------  --------
```
Plus, the results on the 'test' split with 150 framses are as follows (dynamic_stereo_dr_sf.pth on DS testset):
```
===== Perception results =====
-----------------------  ---------
disp_epe_bad_0.5px       6.69365
disp_epe_bad_1px         3.32043
disp_epe_bad_2px         1.60813
disp_epe_bad_3px         0.926385
disp_epe_mean            0.210156
disp_temp_epe_bad_0.5px  1.40267
disp_temp_epe_bad_1px    0.684252
disp_temp_epe_bad_2px    0.345461
disp_temp_epe_bad_3px    0.228157
disp_temp_epe_mean       0.0746498
-----------------------  ---------
```
