### ISSUE TITLE
Inquiry about the real dataset

### ISSUE THREAD

**Issue by TomTomTommi** [facebookresearch/dynamic_stereo#14]
Hi,

I am interested in the proposed real dataset. I would love to know what device you used to capture stereo videos of real scenes. Thanks so much!

**Comment by EmmaThompson123** [comment]
Do you mean this : 
![img_v3_029u_f8062b4d-6731-4a21-95b3-4a0960797b9g](https://github.com/facebookresearch/dynamic_stereo/assets/138575543/3cf1b4c2-d652-4bc2-99c9-e4205e514055)
I am curious about what is the baseline in mm of camera ~
