### ISSUE TITLE
camera intrinsics and extrinsics

### ISSUE THREAD

**Issue by hnj5247** [facebookresearch/dynamic_stereo#17]
Hello, Thank you for your great work.

I'm curious where Dynamic Replica dataset's camera intrinsics and extrinsics information is saved.
I would like to get the camera pose information for each img frame.

Thank you

**Comment by hnj5247** [comment]
Found it in frame_annotations_{}.jgz file

**Comment by wyddmw** [comment]
> Found it in frame_annotations_{}.jgz file

Hi, have you figured out how to use the extrinsic and intrinsic data?
