### ISSUE TITLE
About Real Data

### ISSUE THREAD

**Issue by johnbhlm** [facebookresearch/dynamic_stereo#3]
First of all,  thanks for your wonderful job.
If the real-data collection contains depth ground truth?
I don't discover the scene depth;  just find the depth of people. If so, how can the deep ground truth be produced?

**Comment by nikitakaraevv** [comment]
Thank you for the question, @johnbhlm! 
Unfortunately, ground truth depth obtained from sensors is not available for this dataset. The "real" subset contains depth predicted by a single-frame disparity estimator (in this case, RAFT Stereo) and converted to depth using camera parameters. 
Indeed, it seems that this folder includes depth segmented with people masks. Thank you for bringing this to our attention! We will exclude this folder from the new version of the dataset to prevent any confusion.

**Comment by johnbhlm** [comment]
thanks your reply
