### ISSUE TITLE
About Dynamic-Replica Generation 

### ISSUE THREAD

**Issue by rwn17** [facebookresearch/dynamic_stereo#5]
Hi dynamic_stereo team,

Great work on the project! I was wondering which simulator you use for generating the dynamic-replica? Also, are there plans to open-source the related script?

Thanks in advance,
Weining

**Comment by nikitakaraevv** [comment]
Hi @rwn17, thank you!

We primarily used our own data and code to generate Dynamic Replica sequences. Afterwards, we utilized the [Python API for Blender ](https://docs.blender.org/api/current/info_overview.html) and [Pytorch3D](https://pytorch3d.org/) to render them. As of now, we do not have any plans to release the code.

Kind regards,
Nikita

**Comment by rwn17** [comment]
Thanks for your prompt reply @nikitakaraevv ! That really helps me a lot.

Bests,
Weining
