### ISSUE TITLE
Release time of the optical flow and long range pixel trajectories

### ISSUE THREAD

**Issue by chenjiajie9811** [facebookresearch/dynamic_stereo#7]
Hi, thank you so much for the great works and the datasets! You mentioned in the repo that the optical flow and the long range pixel trajectories will be coming in June, do you have a more specific release time? I will really appreciate that!

**Comment by nikitakaraevv** [comment]
Hi, thank you for the question! I'm working on that right now. I'll try to release them by the end of this week.

**Comment by nikitakaraevv** [comment]
Hi @chenjiajie9811,  we released optical flow and long-range trajectories. Please take a look at [this notebook](https://github.com/facebookresearch/dynamic_stereo/blob/main/notebooks/Dynamic_Replica_demo.ipynb).

**Comment by chenjiajie9811** [comment]
Awesome! Thank you so much!
